name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: rustup toolchain install nightly --component clippy && rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: style
      run: cargo fmt -- --check
    - name: clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
